//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _320PracApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Manakov
    {
        public int ID { get; set; }
        public string Surname { get; set; }
    }
}
